// SPDX-License-Identifier: EPL-2.0

/**
 * T1 (AD-1) — inline-image render tests.
 *
 * Covers RenderOptions.inlineImages end-to-end through the public
 * `render()` entry point. The image seam reachable from a rendered graph is
 * the HTML `<IMG>` cell path (`emitHtmlImg` → `renderer.usershape()`) — node
 * `image=`/`shapefile=` shapes are not yet ported (bindShape falls back to a
 * plain box, @see src/common/shapes.ts:bindShape), so that is the path
 * exercised here; both routes share the same `usershape()` seam.
 *
 * @see lib/gvc/gvrender.c:gvrender_usershape
 * @see plans/docs-overhaul/decisions.md#image-api
 */

import { afterEach, describe, expect, it } from 'vitest';
import { parse } from '../parser/index.js';
import { render } from './public.js';
import { setImageSizer } from '../gvc/usershape.js';
import { setImageResolver } from '../gvc/image-resolver.js';

const IMG_DOT =
  'digraph { A [shape=plaintext label=<<TABLE><TR><TD>' +
  '<IMG SRC="logo.png"/></TD></TR></TABLE>>]; }';

/**
 * Byte-identical baseline captured from a pristine checkout of `main`
 * (`git show HEAD:src/render/{svg,public}.ts` + `src/gvc/device.ts`, run in
 * an isolated `git worktree` before any T1 edits) rendering `IMG_DOT` with
 * `setImageSizer` resolving `logo.png` to 24x12pt. This guards the hard
 * stop: unset/false `inlineImages` must never change a single byte of
 * existing output.
 */
const BASELINE_SVG =
  '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n' +
  '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n' +
  ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n' +
  '<!-- Generated by graphviz-ts -->\n' +
  '<svg width="62pt" height="44pt"\n' +
  '     viewBox="0.00 0.00 62.00 44.00"\n' +
  '     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n' +
  '<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">\n' +
  '<polygon fill="white" stroke="none" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>\n' +
  '<g id="node1" class="node">\n' +
  '<title>A</title>\n' +
  '<polygon fill="none" stroke="black" points="12,-9 12,-27 42,-27 42,-9 12,-9"/>\n' +
  '<image xlink:href="logo.png" width="24px" height="12px" ' +
  'preserveAspectRatio="xMinYMin meet" x="15" y="-24"/>\n' +
  '<polygon fill="none" stroke="black" points="9,-6 9,-30 45,-30 45,-6 9,-6"/>\n' +
  '</g>\n' +
  '</g>\n' +
  '</svg>\n';

describe('T1 — RenderOptions.inlineImages', () => {
  afterEach(() => {
    setImageSizer(null);
    setImageResolver(null);
  });

  it('inlineImages unset ⇒ byte-identical to the pre-AD-1 baseline', () => {
    setImageSizer((s) => (s === 'logo.png' ? { w: 24, h: 12 } : null));
    const g = parse(IMG_DOT);
    const svg = render(g, 'svg');
    expect(svg).toBe(BASELINE_SVG);
  });

  it('inlineImages: false ⇒ also byte-identical to the baseline', () => {
    setImageSizer((s) => (s === 'logo.png' ? { w: 24, h: 12 } : null));
    const g = parse(IMG_DOT);
    const svg = render(g, 'svg', { inlineImages: false });
    expect(svg).toBe(BASELINE_SVG);
  });

  it('inlineImages: true + resolver hit ⇒ data: URI, no raw src href', () => {
    setImageSizer((s) => (s === 'logo.png' ? { w: 24, h: 12 } : null));
    const pngBytes = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a]);
    setImageResolver((src) => (src === 'logo.png' ? { bytes: pngBytes, mime: 'image/png' } : null));
    const g = parse(IMG_DOT);
    const svg = render(g, 'svg', { inlineImages: true });
    expect(svg).toContain('xlink:href="data:image/png;base64,iVBORw0K"');
    expect(svg).not.toContain('xlink:href="logo.png"');
  });

  it('inlineImages: true, no resolver registered ⇒ graceful miss, raw href', () => {
    setImageSizer((s) => (s === 'logo.png' ? { w: 24, h: 12 } : null));
    const g = parse(IMG_DOT);
    const svg = render(g, 'svg', { inlineImages: true });
    expect(svg).toContain('xlink:href="logo.png"');
  });

  it('bare Uint8Array resolver result infers mime from extension (.jpg)', () => {
    setImageSizer((s) => (s === 'pic.jpg' ? { w: 24, h: 12 } : null));
    const jpgBytes = new Uint8Array([0xff, 0xd8, 0xff]);
    setImageResolver((src) => (src === 'pic.jpg' ? jpgBytes : null));
    const g = parse(
      'digraph { A [shape=plaintext label=<<TABLE><TR><TD>' +
        '<IMG SRC="pic.jpg"/></TD></TR></TABLE>>]; }',
    );
    const svg = render(g, 'svg', { inlineImages: true });
    expect(svg).toContain('xlink:href="data:image/jpeg;base64,');
  });
});
