// SPDX-License-Identifier: EPL-2.0

/**
 * SVG document prologue and graph group open/close helpers.
 * Split from svg-helpers.ts to keep that module under the size cap.
 *
 * NOTE: no ${...} template literals here — Lizard bug #2 (see
 * svg-helpers.ts file header).
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_graph
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */

import type { Graph } from '../model/graph.js';
import type { Box } from '../model/geom.js';
import type { RenderJob } from '../gvc/job.js';
import { escapeXml, SVG_PAD } from './svg-helpers.js';

const SVG_XML_DECL =
  '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n';
const SVG_DOCTYPE =
  '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n' +
  ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n';
const SVG_GENERATOR_COMMENT = '<!-- Generated by graphviz-ts -->\n';

/** Root graph group id always matches C's GD_graph_id counter. */
export function graphGroupId(_name: string): string {
  return 'graph0';
}

/** Emit SVG tag. ViewBox starts at (0,0); group translate absorbs bb.ll offset. */
export function emitSvgTag(job: RenderJob): void {
  const bb = job.bb;
  const contentW = Math.round(bb.ur.x - bb.ll.x);
  const contentH = Math.round(bb.ur.y - bb.ll.y);
  const w = contentW + 2 * SVG_PAD;
  const h = contentH + 2 * SVG_PAD;
  job.write('<svg width="' + String(w) + 'pt" height="' + String(h) + 'pt"\n');
  // viewBox always starts at (0,0); group translate accounts for bb.ll offset
  job.write('     viewBox="0.00 0.00 ' + String(w) + '.00 ' + String(h) + '.00"\n');
  job.write('     xmlns="http://www.w3.org/2000/svg"');
  job.write(' xmlns:xlink="http://www.w3.org/1999/xlink">\n');
}

/**
 * Emit the graph `<g>` open tag with y-flip transform.
 *
 * translate(PAD, contentH+PAD) maps graphviz origin (0,0) to the
 * bottom-left corner of the padded viewport.  Combined with devscale.y=-1,
 * a node at graphviz (x,y) appears at SVG (x+PAD, h-PAD-y).
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */
export function emitGraphGroupOpen(
  graphId: string,
  tx: number,
  ty: number,
  job: RenderJob,
): void {
  job.write('<g id="' + graphId + '" class="graph"' +
    ' transform="scale(1 1) rotate(0) translate(');
  job.printDouble(tx);
  job.write(' ');
  job.printDouble(ty);
  job.write(')">\n');
}

/**
 * Conditionally emit `<title>` for user-visible graph names.
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */
export function emitGraphTitle(g: Graph, job: RenderJob): void {
  if (g.name.length > 0 && g.name[0] !== '%') {
    job.write('<title>' + escapeXml(g.name) + '</title>\n');
  }
}

/**
 * Emit white background polygon covering the full padded content area.
 *
 * Coordinates are in the group's local frame (y-flipped via devscale.y=-1):
 *   x: [bb.ll.x - PAD, bb.ur.x + PAD]
 *   y (flipped): [-(bb.ur.y + PAD), -(bb.ll.y - PAD)]
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */
export function emitGraphBackground(bb: Box, job: RenderJob): void {
  const left   = bb.ll.x - SVG_PAD;
  const right  = bb.ur.x + SVG_PAD;
  const top    = -(bb.ur.y + SVG_PAD);
  const bottom = -(bb.ll.y - SVG_PAD);
  const corners: [number, number][] = [
    [left, bottom], [left, top], [right, top], [right, bottom], [left, bottom],
  ];
  job.write('<polygon fill="white" stroke="none" points="');
  corners.forEach(([px, py], i) => {
    if (i > 0) job.write(' ');
    job.printDouble(px);
    job.write(',');
    job.printDouble(py);
  });
  job.write('"/>\n');
}

/**
 * Emit SVG prologue, padded `<svg>` tag, graph `<g>` with y-flip transform,
 * and white background polygon.
 *
 * Y-axis: Graphviz y-up vs SVG y-down.  devscale.y=-1 negates all y coords
 * before renderer callbacks; the graph `<g>` translate(PAD, contentH+PAD)
 * places the Graphviz origin at the bottom-left of the padded viewport.
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_graph
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */
export function svgBeginGraph(g: Graph, job: RenderJob): void {
  job.devscale = { x: 1, y: -1 };
  job.directed = g.kind === 'directed' || g.kind === 'strict-directed';
  job.write(SVG_XML_DECL);
  job.write(SVG_DOCTYPE);
  job.write(SVG_GENERATOR_COMMENT);
  emitSvgTag(job);
  const bb = job.bb;
  // tx/ty account for bb.ll offset so viewBox can stay at (0,0)
  const tx = SVG_PAD - bb.ll.x;
  const ty = bb.ur.y + SVG_PAD;
  emitGraphGroupOpen(graphGroupId(g.name), tx, ty, job);
  emitGraphTitle(g, job);
  emitGraphBackground(bb, job);
}

/**
 * Close the graph `<g>` group and the `<svg>` element.
 * @see plugin/core/gvrender_core_svg.c:svg_end_graph
 */
export function svgEndGraph(job: RenderJob): void {
  job.write('</g>\n');
  job.write('</svg>\n');
}
