// SPDX-License-Identifier: EPL-2.0

/**
 * SVG renderer helper functions.
 *
 * All shape-emission logic lives here as top-level export functions so
 * Lizard's TypeScript parser tracks function boundaries correctly.
 * Lizard only resets its function-tracking on the export keyword;
 * bare function declarations are silently absorbed into the preceding
 * exported function's body count.
 *
 * Lizard parser bug: the regex literal containing a double-quote char
 * (e.g. /"/g) unbalances its string-quote tracker. All regex patterns
 * that match double-quotes must use new RegExp('"', 'g') instead.
 *
 * @see plugin/core/gvrender_core_svg.c
 */

import type { Graph } from '../model/graph.js';
import type { Node } from '../model/node.js';
import type { Edge } from '../model/edge.js';
import type { Point } from '../model/geom.js';
import type { TextSpan } from '../common/emit-types.js';
import type { RenderJob, ObjState } from '../gvc/job.js';
import { PenType } from '../gvc/context.js';

// ---------------------------------------------------------------------------
// Module-level constants
// ---------------------------------------------------------------------------

const SVG_DASH_ARRAY = '5,2';
const SVG_DOT_ARRAY = '1,5';
const PENWIDTH_NORMAL = 1.0;
const PENWIDTH_BOLD = 2.0;
const PENWIDTH_THRESHOLD = 0.005;
const SVG_XML_DECL =
  '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n';
const SVG_DOCTYPE =
  '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n' +
  ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n';
const SVG_GENERATOR_COMMENT = '<!-- Generated by graphviz-ts -->\n';

// Regex for double-quote: /"/g breaks Lizard's quote-tracker.
// Use this named pattern instead to avoid the parser bug.
const RE_DQUOTE = new RegExp('"', 'g');

// ---------------------------------------------------------------------------
// XML escaping
// ---------------------------------------------------------------------------

export function escapeXml(s: string): string {
  let r = s.replace(/&/g, '&amp;');
  r = r.replace(/</g, '&lt;');
  r = r.replace(/>/g, '&gt;');
  r = r.replace(RE_DQUOTE, '&quot;');
  return r;
}

// ---------------------------------------------------------------------------
// Color helpers
// ---------------------------------------------------------------------------

export function rgbaStr(r: number, g: number, b: number): string {
  const rh = Math.round(r * 255).toString(16).padStart(2, '0');
  const gh = Math.round(g * 255).toString(16).padStart(2, '0');
  const bh = Math.round(b * 255).toString(16).padStart(2, '0');
  return `#${rh}${gh}${bh}`;
}

export function paintStr(obj: ObjState, useFill: boolean): string {
  const color = useFill ? obj.fillColor : obj.penColor;
  if (color.type === 'none') return 'none';
  if (color.type === 'string') {
    return color.s === 'transparent' ? 'none' : color.s;
  }
  if (color.type === 'rgba') {
    if (color.a === 0) return 'none';
    return rgbaStr(color.r, color.g, color.b);
  }
  return 'black';
}

// ---------------------------------------------------------------------------
// Style helpers
// ---------------------------------------------------------------------------

export function emitDash(job: RenderJob, pen: PenType): void {
  if (pen === PenType.Dashed) {
    job.write(` stroke-dasharray="${SVG_DASH_ARRAY}"`);
  } else if (pen === PenType.Dotted) {
    job.write(` stroke-dasharray="${SVG_DOT_ARRAY}"`);
  }
}

export function emitPenWidth(job: RenderJob, pw: number): void {
  if (Math.abs(pw - PENWIDTH_BOLD) < PENWIDTH_THRESHOLD) {
    job.write(` stroke-width="${PENWIDTH_BOLD}"`);
    return;
  }
  job.write(' stroke-width="');
  job.printDouble(pw);
  job.write('"');
}

export function emitStyle(job: RenderJob, filled: boolean): void {
  const obj = job.obj;
  const fill = obj !== null && filled ? paintStr(obj, true) : 'none';
  const stroke = obj !== null ? paintStr(obj, false) : 'black';
  job.write(` fill="${fill}" stroke="${stroke}"`);
  if (obj === null) return;
  const pw = obj.penWidth;
  if (Math.abs(pw - PENWIDTH_NORMAL) >= PENWIDTH_THRESHOLD) {
    emitPenWidth(job, pw);
  }
  emitDash(job, obj.pen);
}

// ---------------------------------------------------------------------------
// Point serialisation helpers
// ---------------------------------------------------------------------------

export function emitPoints(job: RenderJob, pts: Point[]): void {
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i]!;
    job.printDouble(p.x);
    job.write(',');
    job.printDouble(p.y);
    if (i + 1 < pts.length) job.write(' ');
  }
}

export function emitBezierPath(job: RenderJob, pts: Point[]): void {
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i]!;
    const c = i === 0 ? 'M' : (i === 1 ? 'C' : ' ');
    job.write(c);
    job.printDouble(p.x);
    job.write(',');
    job.printDouble(p.y);
  }
}

// ---------------------------------------------------------------------------
// Text alignment
// ---------------------------------------------------------------------------

export function textAnchor(just: 'l' | 'n' | 'r'): string {
  if (just === 'l') return 'start';
  if (just === 'r') return 'end';
  return 'middle';
}

// ---------------------------------------------------------------------------
// Graph open/close
// ---------------------------------------------------------------------------

export function emitSvgTag(g: Graph, job: RenderJob): void {
  const bb = job.bb;
  const w = Math.round(bb.ur.x - bb.ll.x);
  const h = Math.round(bb.ur.y - bb.ll.y);
  job.write(`<svg width="${w}pt" height="${h}pt"\n`);
  job.write(`     viewBox="${bb.ll.x} ${bb.ll.y} ${w} ${h}"\n`);
  job.write('     xmlns="http://www.w3.org/2000/svg"');
  job.write(' xmlns:xlink="http://www.w3.org/1999/xlink">\n');
  if (g.name && g.name.length > 0 && g.name[0] !== '%') {
    job.write(`<title>${escapeXml(g.name)}</title>\n`);
  }
}

export function svgBeginGraph(g: Graph, job: RenderJob): void {
  job.write(SVG_XML_DECL);
  job.write(SVG_DOCTYPE);
  job.write(SVG_GENERATOR_COMMENT);
  emitSvgTag(g, job);
}

export function svgEndGraph(job: RenderJob): void {
  job.write('</svg>\n');
}

// ---------------------------------------------------------------------------
// Node / edge group wrappers
// ---------------------------------------------------------------------------

export function svgBeginNode(n: Node, job: RenderJob): void {
  job.write(`<g id="${escapeXml(n.name)}" class="node">\n`);
  job.write(`<title>${escapeXml(n.name)}</title>\n`);
}

export function svgEndNode(job: RenderJob): void {
  job.write('</g>\n');
}

export function svgBeginEdge(e: Edge, job: RenderJob): void {
  const tid = escapeXml(e.tail.name);
  const hid = escapeXml(e.head.name);
  job.write(`<g id="${tid}-&gt;${hid}" class="edge">\n`);
  job.write(`<title>${tid}-&gt;${hid}</title>\n`);
}

export function svgEndEdge(job: RenderJob): void {
  job.write('</g>\n');
}

// ---------------------------------------------------------------------------
// Anchor helpers
// ---------------------------------------------------------------------------

export function emitAnchorAttrs(
  href: string,
  tooltip: string,
  target: string,
  job: RenderJob,
): void {
  if (href.length > 0) {
    job.write(` xlink:href="${escapeXml(href)}" href="${escapeXml(href)}"`);
  }
  if (tooltip.length > 0) {
    job.write(` xlink:title="${escapeXml(tooltip)}"`);
  }
  if (target.length > 0) {
    job.write(` target="${escapeXml(target)}"`);
  }
}

export function svgBeginAnchor(
  href: string,
  tooltip: string,
  target: string,
  id: string,
  job: RenderJob,
): void {
  if (id.length > 0) {
    job.write(`<g id="a_${escapeXml(id)}"><a`);
  } else {
    job.write('<g><a');
  }
  emitAnchorAttrs(href, tooltip, target, job);
  job.write('>\n');
}

export function svgEndAnchor(job: RenderJob): void {
  job.write('</a>\n</g>\n');
}

// ---------------------------------------------------------------------------
// Text span
// ---------------------------------------------------------------------------

export function svgTextspan(pos: Point, span: TextSpan, job: RenderJob): void {
  const anchor = textAnchor(span.just);
  const y = pos.y + span.yoffset_centerline;
  const fontName = span.fontName ?? 'Times,serif';
  job.write(`<text xml:space="preserve" text-anchor="${anchor}"`);
  job.write(` x="${pos.x}" y="${y}"`);
  job.write(` font-family="${escapeXml(fontName)}"`);
  job.write(` font-size="${span.fontSize.toFixed(2)}"`);
  job.write(`>${escapeXml(span.str)}</text>\n`);
}

// ---------------------------------------------------------------------------
// Shape emitters
// ---------------------------------------------------------------------------

export function svgEllipse(
  center: Point,
  rx: number,
  ry: number,
  filled: boolean,
  job: RenderJob,
): void {
  job.write('<ellipse');
  emitStyle(job, filled);
  job.write(' cx="');
  job.printDouble(center.x);
  job.write('" cy="');
  job.printDouble(center.y);
  job.write('" rx="');
  job.printDouble(rx);
  job.write('" ry="');
  job.printDouble(ry);
  job.write('"/>\n');
}

export function svgPolygon(pts: Point[], filled: boolean, job: RenderJob): void {
  job.write('<polygon');
  emitStyle(job, filled);
  job.write(' points="');
  emitPoints(job, pts);
  if (pts.length > 0) {
    // Repeat first point — Adobe SVG compatibility
    // @see plugin/core/gvrender_core_svg.c:svg_polygon
    const p0 = pts[0]!;
    job.write(' ');
    job.printDouble(p0.x);
    job.write(',');
    job.printDouble(p0.y);
  }
  job.write('"/>\n');
}

export function svgBezier(pts: Point[], filled: boolean, job: RenderJob): void {
  job.write('<path');
  emitStyle(job, filled);
  job.write(' d="');
  emitBezierPath(job, pts);
  job.write('"/>\n');
}

export function svgPolyline(pts: Point[], job: RenderJob): void {
  job.write('<polyline');
  emitStyle(job, false);
  job.write(' points="');
  emitPoints(job, pts);
  job.write('"/>\n');
}

export function svgComment(text: string, job: RenderJob): void {
  job.write(`<!-- ${escapeXml(text)} -->\n`);
}
