// SPDX-License-Identifier: EPL-2.0

/**
 * SVG document prologue and graph group open/close helpers.
 * Split from svg-helpers.ts to keep that module under the size cap.
 *
 * NOTE: no ${...} template literals here — Lizard bug #2 (see
 * svg-helpers.ts file header).
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_graph
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */

import type { Graph } from '../model/graph.js';
import type { Box, Point } from '../model/geom.js';
import type { RenderJob } from '../gvc/job.js';
import { createObjState, ObjType } from '../gvc/job.js';
import { FillType } from '../gvc/context.js';
import { escapeXml, SVG_PAD } from './svg-helpers.js';
import { resolveRenderColor } from './color-resolve.js';
import { parseGradientSpec } from '../common/htmltable-emit-fill.js';
import { findStopColor, parseStyleFlags } from '../common/style-resolve.js';
import {
  emitLinearGradient,
  emitRadialGradient,
  gradientId,
} from './svg-gradient.js';

const SVG_XML_DECL =
  '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n';
const SVG_DOCTYPE =
  '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n' +
  ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n';
const SVG_GENERATOR_COMMENT = '<!-- Generated by graphviz-ts -->\n';

/** Sentinel meaning "emit no background polygon" (bgcolor=transparent on SVG). */
const BGCOLOR_TRANSPARENT = '\x00transparent';

/**
 * Resolved gradient spec for a two-color bgcolor.
 * Groups the fields that emitGradientBackground needs beyond bb+job.
 * @see lib/common/emit.c:emit_background:1503
 */
interface BgGradientSpec {
  fillColor: string;
  stopColor: string;
  frac: number;
  angle: number;
  radial: boolean;
}

/** Root graph group id always matches C's GD_graph_id counter. */
export function graphGroupId(_name: string): string {
  return 'graph0';
}

/** Emit SVG tag. ViewBox starts at (0,0); group translate absorbs bb.ll offset. */
export function emitSvgTag(job: RenderJob): void {
  const bb = job.bb;
  const contentW = Math.round(bb.ur.x - bb.ll.x);
  const contentH = Math.round(bb.ur.y - bb.ll.y);
  const w = contentW + 2 * SVG_PAD;
  const h = contentH + 2 * SVG_PAD;
  job.write('<svg width="' + String(w) + 'pt" height="' + String(h) + 'pt"\n');
  // viewBox always starts at (0,0); gvPostprocess normalises bb.ll to (0,0) before render
  job.write('     viewBox="0.00 0.00 ' + String(w) + '.00 ' + String(h) + '.00"\n');
  job.write('     xmlns="http://www.w3.org/2000/svg"');
  job.write(' xmlns:xlink="http://www.w3.org/1999/xlink">\n');
}

/**
 * Emit the graph `<g>` open tag with y-flip transform.
 *
 * translate(PAD, contentH+PAD) maps graphviz origin (0,0) to the
 * bottom-left corner of the padded viewport.  Combined with devscale.y=-1,
 * a node at graphviz (x,y) appears at SVG (x+PAD, h-PAD-y).
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */
export function emitGraphGroupOpen(
  graphId: string,
  tx: number,
  ty: number,
  job: RenderJob,
): void {
  job.write('<g id="' + graphId + '" class="graph"' +
    ' transform="scale(1 1) rotate(0) translate(');
  job.printDouble(tx);
  job.write(' ');
  job.printDouble(ty);
  job.write(')">\n');
}

/**
 * Conditionally emit `<title>` for user-visible graph names.
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 */
export function emitGraphTitle(g: Graph, job: RenderJob): void {
  if (g.name.length > 0 && g.name[0] !== '%') {
    job.write('<title>' + escapeXml(g.name) + '</title>\n');
  }
}

/**
 * Resolve the graph bgcolor attribute to the color string to use for the
 * background polygon, or the BGCOLOR_TRANSPARENT sentinel to suppress it.
 *
 * Precedence mirrors emit_background (lib/common/emit.c:1476-1530):
 *   - absent/empty → "white" (default white paper)
 *   - "transparent" → BGCOLOR_TRANSPARENT sentinel (SVG is truecolor)
 *   - gradient "c1:c2" → first solid color (AD3)
 *   - else → the literal color string
 *
 * @see lib/common/emit.c:emit_background:1476
 */
export function resolveGraphBgcolor(bgcolorAttr: string | undefined): string {
  if (!bgcolorAttr || bgcolorAttr.length === 0) return 'white';
  if (bgcolorAttr === 'transparent') return BGCOLOR_TRANSPARENT;
  const grad = parseGradientSpec(bgcolorAttr);
  return grad !== null ? grad[0] : bgcolorAttr;
}

/**
 * Emit background polygon covering the full padded content area.
 *
 * Omits the polygon entirely when resolvedColor is the transparent sentinel.
 * Coordinates are in the group's local frame (y-flipped via devscale.y=-1):
 *   x: [bb.ll.x - PAD, bb.ur.x + PAD]
 *   y (flipped): [-(bb.ur.y + PAD), -(bb.ll.y - PAD)]
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 * @see lib/common/emit.c:emit_background:1476
 */
export function emitGraphBackground(bb: Box, resolvedColor: string, job: RenderJob): void {
  if (resolvedColor === BGCOLOR_TRANSPARENT) return;
  const left   = bb.ll.x - SVG_PAD;
  const right  = bb.ur.x + SVG_PAD;
  const top    = -(bb.ur.y + SVG_PAD);
  const bottom = -(bb.ll.y - SVG_PAD);
  const corners: [number, number][] = [
    [left, bottom], [left, top], [right, top], [right, bottom], [left, bottom],
  ];
  job.write('<polygon fill="' + resolvedColor + '" stroke="none" points="');
  corners.forEach(([px, py], i) => {
    if (i > 0) job.write(' ');
    job.printDouble(px);
    job.write(',');
    job.printDouble(py);
  });
  job.write('"/>\n');
}

/**
 * Compute the 4 background-polygon corner points in graphviz (y-up) space.
 * Passed to getGradientPoints inside emitLinearGradient.
 * @see lib/common/emit.c:emit_background:1517 (gvrender_box with clip)
 */
function bgGradientPts(bb: Box): Point[] {
  const left   = bb.ll.x - SVG_PAD;
  const right  = bb.ur.x + SVG_PAD;
  const bottom = bb.ll.y - SVG_PAD;
  const top    = bb.ur.y + SVG_PAD;
  return [
    { x: left,  y: bottom },
    { x: left,  y: top    },
    { x: right, y: top    },
    { x: right, y: bottom },
  ];
}

/**
 * Write background polygon element with gradient fill url reference.
 * Coords identical to emitGraphBackground; only fill changes.
 * @see plugin/core/gvrender_core_svg.c:svg_polygon:686
 */
function writeGradientPolygon(bb: Box, id: string, job: RenderJob): void {
  const left   = bb.ll.x - SVG_PAD;
  const right  = bb.ur.x + SVG_PAD;
  const top    = -(bb.ur.y + SVG_PAD);
  const bottom = -(bb.ll.y - SVG_PAD);
  const corners: [number, number][] = [
    [left, bottom], [left, top], [right, top], [right, bottom], [left, bottom],
  ];
  job.write('<polygon fill="url(#' + id + ')" stroke="none" points="');
  corners.forEach(([px, py], i) => {
    if (i > 0) job.write(' ');
    job.printDouble(px);
    job.write(',');
    job.printDouble(py);
  });
  job.write('"/>\n');
}

/**
 * Emit the gradient background for a graph with a two-color bgcolor.
 * Pushes a temporary ObjState, emits the <defs> gradient, writes the polygon.
 *
 * The gradient id is prefixed "graph0_" to match C's svg_gradstyle behaviour
 * when obj->id is set: graph0_l_0 / graph0_r_0.
 *
 * @see lib/common/emit.c:emit_background:1503-1519
 * @see plugin/core/gvrender_core_svg.c:svg_gradstyle:572
 * @see plugin/core/gvrender_core_svg.c:svg_rgradstyle:608
 */
function emitGradientBackground(bb: Box, spec: BgGradientSpec, job: RenderJob): void {
  const obj = createObjState(ObjType.RootGraph);
  obj.id = 'graph0';
  obj.fillColor = resolveRenderColor(spec.fillColor);
  obj.stopColor = resolveRenderColor(spec.stopColor);
  obj.gradientFrac = spec.frac;
  obj.gradientAngle = spec.angle;
  obj.fill = spec.radial ? FillType.Radial : FillType.Linear;
  job.pushObj(obj);
  let gid: string;
  if (spec.radial) {
    gid = gradientId('graph0', 'r', job.radialGradId++);
    emitRadialGradient(job, gid);
  } else {
    gid = gradientId('graph0', 'l', job.linearGradId++);
    emitLinearGradient(job, bgGradientPts(bb), gid);
  }
  job.popObj();
  writeGradientPolygon(bb, gid, job);
}

/**
 * Resolve BgGradientSpec from graph attrs when bgcolor is a two-color spec.
 * Returns null when bgcolor is not a gradient.
 * @see lib/common/emit.c:emit_background:1503-1516
 */
function resolveBgGradientSpec(g: Graph, bgcolorAttr: string): BgGradientSpec | null {
  const stop = findStopColor(bgcolorAttr);
  if (stop === null) return null;
  const flags = parseStyleFlags(g.attrs.get('style'));
  const angleStr = g.attrs.get('gradientangle');
  const angle = angleStr ? (parseInt(angleStr, 10) || 0) : 0;
  return { fillColor: stop.fillColor, stopColor: stop.stopColor, frac: stop.frac, angle, radial: flags.radial };
}

/**
 * Resolve and emit the background — gradient or solid/transparent.
 * Separated to keep svgBeginGraph under the 30-line body limit.
 * @see lib/common/emit.c:emit_background:1476
 */
function emitBgcolorBackground(g: Graph, bb: Box, bgcolorAttr: string | undefined, job: RenderJob): void {
  if (!bgcolorAttr || bgcolorAttr.length === 0 || bgcolorAttr === 'transparent') {
    emitGraphBackground(bb, resolveGraphBgcolor(bgcolorAttr), job);
    return;
  }
  const spec = resolveBgGradientSpec(g, bgcolorAttr);
  if (spec !== null) {
    emitGradientBackground(bb, spec, job);
    return;
  }
  emitGraphBackground(bb, resolveGraphBgcolor(bgcolorAttr), job);
}

/**
 * Emit SVG prologue, padded `<svg>` tag, graph `<g>` with y-flip transform,
 * and background polygon (color resolved from bgcolor attr).
 *
 * Y-axis: Graphviz y-up vs SVG y-down.  devscale.y=-1 negates all y coords
 * before renderer callbacks; the graph `<g>` translate(PAD, contentH+PAD)
 * places the Graphviz origin at the bottom-left of the padded viewport.
 *
 * @see plugin/core/gvrender_core_svg.c:svg_begin_graph
 * @see plugin/core/gvrender_core_svg.c:svg_begin_page
 * @see lib/common/emit.c:emit_background:1476
 */
export function svgBeginGraph(g: Graph, job: RenderJob): void {
  job.devscale = { x: 1, y: -1 };
  job.directed = g.kind === 'directed' || g.kind === 'strict-directed';
  job.write(SVG_XML_DECL);
  job.write(SVG_DOCTYPE);
  job.write(SVG_GENERATOR_COMMENT);
  emitSvgTag(job);
  const bb = job.bb;
  // gvPostprocess zeroes bb.ll before render; tx is simply the padding.
  const tx = SVG_PAD;
  const ty = bb.ur.y + SVG_PAD;
  emitGraphGroupOpen(graphGroupId(g.name), tx, ty, job);
  emitGraphTitle(g, job);
  const bgcolorAttr = g.attrs.get('bgcolor');
  emitBgcolorBackground(g, bb, bgcolorAttr, job);
}

/**
 * Close the graph `<g>` group and the `<svg>` element.
 * @see plugin/core/gvrender_core_svg.c:svg_end_graph
 */
export function svgEndGraph(job: RenderJob): void {
  job.write('</g>\n');
  job.write('</svg>\n');
}
