// SPDX-License-Identifier: EPL-2.0

/**
 * Regression: the dot `pack` branch must decompose a multi-component graph,
 * lay out each component independently, and polyomino-pack them — C's `doDot`
 * (dotinit.c:doDot ≈437-500) when `pack`/`packmode` is set.
 *
 * For corpus 2458 (`digraph { pack=1; q16; q1 -> q2[label=connected] }`) the two
 * components are `{q16}` and `{q1, q2}`. Native dot (headless 15.1.0) packs them
 * side by side: 132×116, q1/q2 in the left column (cx=27), q16 packed bottom
 * right (cx=97, cy=-32). Without the pack branch the port ranked both components
 * in one structure (164×133, top-aligned) — `pack` was effectively ignored.
 *
 * The edge label "connected" is dropped: C sets `GD_has_labels` on the edge's
 * root, never on the component, so a packed component never gets an edge-label
 * rank (the label is left unplaced). The port mirrors this.
 *
 * @see lib/dotgen/dotinit.c:doDot
 * @see plans/fix-pack-dot-2458/comparisons/T1-investigation.md
 */

import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { renderSvg } from '../../index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOT_2458 = 'digraph {\n\tpack=1\n\tq16\n\tq1 -> q2[label=connected]\n}\n';

/** Extract {svg width/height} and each node's {cx, cy} from rendered SVG. */
function parseLayout(svg: string): {
  width: number; height: number; nodes: Record<string, { cx: number; cy: number }>;
} {
  const wh = /<svg width="(\d+)pt"\s+height="(\d+)pt"/.exec(svg);
  const nodes: Record<string, { cx: number; cy: number }> = {};
  for (const m of svg.matchAll(
    /<title>(q\d+)<\/title>\s*<ellipse[^>]*cx="([-\d.]+)" cy="([-\d.]+)"/g,
  )) {
    nodes[m[1]] = { cx: Number(m[2]), cy: Number(m[3]) };
  }
  return { width: Number(wh?.[1]), height: Number(wh?.[2]), nodes };
}

describe('dot pack branch — multi-component packing (corpus 2458)', () => {
  it('packs {q16} beside {q1,q2} matching headless 15.1.0 geometry', () => {
    const { width, height, nodes } = parseLayout(renderSvg(DOT_2458, 'dot'));
    // Compact packed bbox, not the 164×133 single-structure layout.
    expect(width).toBe(132);
    expect(height).toBe(116);
    // q1/q2 share the left column; q1 above q2.
    expect(nodes['q1'].cx).toBe(27);
    expect(nodes['q2'].cx).toBe(27);
    expect(nodes['q1'].cy).toBeLessThan(nodes['q2'].cy); // -90 < -18
    // q16 packed to the right of the q1/q2 column.
    expect(nodes['q16'].cx).toBe(97);
    expect(nodes['q16'].cx).toBeGreaterThan(nodes['q1'].cx);
  });

  it('drops the edge label inside the packed component (matches C)', () => {
    // C: GD_has_labels lives on the root, never the component, so a packed
    // component gets no edge-label rank and the label is left unplaced.
    expect(renderSvg(DOT_2458, 'dot')).not.toContain('connected');
  });

  it('matches the headless 15.1.0 golden ref body byte-for-byte', () => {
    const ref = readFileSync(
      join(__dirname, '../../../test/golden/refs/pack-2458.svg'),
      'utf8',
    );
    const strip = (s: string): string =>
      s.split('\n')
        .filter((l) => !/^(<!--| -->|<!DOCTYPE|<\?xml|<svg|\s+viewBox|\s+xmlns)/.test(l)
          && !l.includes('Generated by'))
        .join('\n').trim();
    expect(strip(renderSvg(DOT_2458, 'dot'))).toBe(strip(ref));
  });

  it('leaves a single-component graph unaffected by the pack branch', () => {
    // pack set, but one component → C falls back to whole-graph dotLayout.
    const svg = renderSvg('digraph { pack=1; a -> b }', 'dot');
    expect(svg).toContain('<title>a</title>');
    expect(svg).toContain('<title>b</title>');
    expect(svg).toContain('<title>a&#45;&gt;b</title>');
  });
});
